# Use a file like this to manually configure your producer and consumer settings.

title = "Example message config"

# private_key_file = "/Users/acandela/.ssh/id_rsa"
private_key_file = "messages_id_rsa"

# The 'listen' table configures where your machine will be
# listening for messages.

[listen]
external_host = "aim.andrewcandela.com:1053"
internal_host = "10.0.0.176:1053"

# Configure each group below. Groups must have unique identifiers

# Choosing produce -g group_one will send messages to two recipients
[group_one]
name = "Group One"
[[group_one.users]]
host="10.0.0.176:1053"
key="some_key"
[[group_one.users]]
host="aim.andrewcandela.com:1053"
key="some_other_key"

# Choosing produce -g group_two will send messages to one recipient
[group_two]
name = "Group Two"
[[group_two.users]]
host="10.0.0.186:1053"
public_key='''
-----BEGIN RSA PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAw1G2QNnwOYZRGhaCV1Yi
okLAckWbiYXkfTlCub+4n1FapheAX+h45WjIN1UHWdQ8IFkS7knOHkvmXVPW0+Yx
sdewpydRA4hsa8RK5X3HoY8a55AmOhbcDLzomGTTKP+PJLAkFSp4n7ImjXCS1HO0
b6WZfXTk+F+jUVC0oY/174iNG+WbGXxyCJC59448B+3HxcCfJaCt9tXbQO/V+Lrn
A0lgKW1KQ0yultwzpGPMFiZQDS3vuV4UOqCJn9T2X6UpiNqCeZ69//hgW4KTx8tn
r/v7pm1+pYuuf51Vvk+2T9uDG1MChOmvpx5shKG45Yxx/PB8NrB6O/+ezFKU9O4L
MQIDAQAB
-----END RSA PUBLIC KEY-----
'''
